### ISSUE TITLE
[AssetInventory] Crash when searching in a page different than first

### ISSUE THREAD

**Issue by Pedro-Rodrigues30** [lumada-design/hv-uikit-react#2652]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

Using the HvAssetInventory with pagination and searchable items this unexpected behavior occurs.
Situation:
- Multiple pages with items.
- Go to the last page
- In the search box write a letter that the result returns less pages than the one you are at.
- A crash occurs 

<details><summary>Uncaught Error</summary>

`Uncaught Error: CardView(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

    at reconcileChildFibers (react-dom.development.js:14169:1)
    at reconcileChildren (react-dom.development.js:16997:1)
    at updateFunctionComponent (react-dom.development.js:17378:1)
    at beginWork (react-dom.development.js:19063:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)`

` The above error occurred in the <CardView> component:

    at CardView (http://localhost:3000/static/js/bundle.js:2090:5)
    at WithStyles (http://localhost:3000/static/js/bundle.js:33233:31)
    at div
    at Grid (http://localhost:3000/static/js/bundle.js:23847:35)
    at WithStyles (http://localhost:3000/static/js/bundle.js:33233:31)
    at http://localhost:3000/static/js/bundle.js:10851:5
    at WithStyles (http://localhost:3000/static/js/bundle.js:33233:31)
    at div
    at Grid (http://localhost:3000/static/js/bundle.js:23847:35)
    at WithStyles (http://localhost:3000/static/js/bundle.js:33233:31)
    at http://localhost:3000/static/js/bundle.js:10851:5
    at WithStyles (http://localhost:3000/static/js/bundle.js:33233:31)
    at div
    at Grid (http://localhost:3000/static/js/bundle.js:23847:35)
    at WithStyles (http://localhost:3000/static/js/bundle.js:33233:31)
    at http://localhost:3000/static/js/bundle.js:10851:5
    at WithStyles (http://localhost:3000/static/js/bundle.js:33233:31)
    at div
    at Grid (http://localhost:3000/static/js/bundle.js:23847:35)
    at WithStyles (http://localhost:3000/static/js/bundle.js:33233:31)
    at http://localhost:3000/static/js/bundle.js:10851:5
    at WithStyles (http://localhost:3000/static/js/bundle.js:33233:31)
    at div
    at HvAssetInventory (http://localhost:3000/static/js/bundle.js:1390:5)
    at WithStyles (http://localhost:3000/static/js/bundle.js:33233:31)
    at AssetInventory (http://localhost:3000/static/js/bundle.js:238:68)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:32217:24)
    at StylesProvider (http://localhost:3000/static/js/bundle.js:32050:24)
    at HvProvider (http://localhost:3000/static/js/bundle.js:15125:5)
    at ApolloProvider (http://localhost:3000/static/js/bundle.js:115761:19)
    at App
    at Suspense`

</details>

### Expected behavior 🤔

The component should show the items with the correct pagination. 

### Steps to reproduce 🕹

Steps:

1.  Add HvAssetInventory component with pagination
2.  Set data to be searchable with data that can fill multiple pages
3.  Start application and go to the last page
4.  In the search box and with only one interaction write a query that don't have enough results to fill all the pages
5.  A unexpected crash should happen

You can check the code sample, inspired in your example hv-uikit-adoption in this repository: [Asset-Inventory](https://github.com/Pedro-Rodrigues30/asset-inventory-search)

In this repository, I'm using the latest version.
I can also assure you that in another ongoing project, using version "@hv/uikit-react-core": "^3.47.0" this bug also occurs but without a crash. The grid just disappears and shows a weird behaviour with the pagination results.

### Your Environment 🌎

Device: Mobile
OS: Windows 10
Browser: Edge
Version 97.0.1072.69

**Comment by diogofscmariano** [comment]
Hi @Pedro-Rodrigues30 . A fix for this issue as been included in the latest release. Can you please check if it solves on your end?

**Comment by Pedro-Rodrigues30** [comment]
Hi @diogofscmariano . I just checked and yes this is fixed. 
Thanks
