### ISSUE TITLE
AppShell Automatic Setup fails on Windows when including templates

### ISSUE THREAD

**Issue by andrew-kayne** [lumada-design/hv-uikit-react#4054]
### Which UI Kit version is this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

When using the AppShell Automatic Setup process, if I include templates the setup fails due to a file copy failure as shown in the error below:

```
PS Q:\> npx @hitachivantara/hv-uikit-cli@latest create
Need to install the following packages:
@hitachivantara/hv-uikit-cli@1.15.3
Ok to proceed? (y) y
? App name uikit-app
? Use App Shell? Yes
? Do you want to enable App Shell features? If so, choose which: Help Link, Color Mode Switcher, App Switcher
? Use file based routing and automatic menu generation in App Shell? Yes
? Do you want to use templates? If so, choose which: Asset Inventory, List View, Details View, Form
UI kit app generator
Creating a new App Shell app in
Q:\/uikit-app
Creating uikit-app contents
Creating template: AssetInventory
node:fs:453
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^
Error: ENOENT: no such file or directory, open 'Q:\uikit-app\src\pages\AssetInventory\CardView\Q:\uikit-app\src\pages\AssetInventory\CardView.tsx'
    at Object.readFileSync (node:fs:453:20)
    at replaceTemplateImports (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/a83cd8dc6b23afc6/node_modules/@hitachivantara/hv-uikit-cli/src/contents.js:42:28)
    at copyTemplateContents (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/a83cd8dc6b23afc6/node_modules/@hitachivantara/hv-uikit-cli/src/contents.js:129:5)
    at createAppContents (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/a83cd8dc6b23afc6/node_modules/@hitachivantara/hv-uikit-cli/src/contents.js:170:13)
    at async create (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/a83cd8dc6b23afc6/node_modules/@hitachivantara/hv-uikit-cli/src/create.js:128:3) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'Q:\\uikit-app\\src\\pages\\AssetInventory\\CardView\\Q:\\uikit-app\\src\\pages\\AssetInventory\\CardView.tsx'
}
Node.js v20.11.0
```
This fails on both Windows PowerShell or cmd prompt.

### Expected behavior 🤔

The Automatic Setup should not fail with templates on Windows.

### Steps to reproduce 🕹

Using Windows PowerShell or cmd prompt, run the App Shell Automatic Setup using the defaults and including all templates. The exact options can be seen in the error output above.

### Your Environment 🌎

Node: v20.11.0

**Comment by zettca** [comment]
Hey @andrew-kayne, thanks for reporting 👍

Is this something you're willing to contribute a fix to? 😃

**Comment by VGervasio** [comment]
Fixed in https://github.com/lumada-design/hv-uikit-cli/pull/28 .
